feat: Outputs result
kobayu858/sched_sim_rust pull request #17
Opened 2023-05-15 07:42 UTC by kobayu858

###SUMMARY
- Preparing to output test results
- Creating the file
- Output information on used dag in yaml

2023-05-16 06:28 UTC, atsushi421 requested changes

2023-05-16 06:28 UTC, atsushi421 commented on lib/src/output.rs
> +struct DAGSet {
```suggestion
struct DAGSetInfo {
```

2023-05-16 06:28 UTC, atsushi421 commented on lib/src/output.rs
> +struct DAG {
```suggestion
struct DAGInfo {
```

2023-05-16 06:28 UTC, atsushi421 commented on lib/src/output.rs
> +    let mut dag_instances = Vec::new();
```suggestion
    let mut each_dag_info = Vec::new();
```

2023-05-16 06:28 UTC, atsushi421 commented on lib/src/output.rs
> +        let dag_instance = DAG {
```suggestion
        let dag_info = DAGInfo {
```

2023-05-16 06:28 UTC, atsushi421 commented on lib/src/output.rs
> +    let dag_set = DAGSet {
```suggestion
    let dag_set_info = DAGSetInfo {
```

2023-05-16 08:15 UTC, kobayu858 commented on lib/src/output.rs
> +struct DAGSet {
accept your suggestion.

2023-05-16 08:15 UTC, kobayu858 commented on lib/src/output.rs
> +struct DAG {
accept your suggestion.

2023-05-16 08:15 UTC, kobayu858 commented on lib/src/output.rs
> +    let mut dag_instances = Vec::new();
accept your suggestion.

2023-05-16 08:15 UTC, kobayu858 commented on lib/src/output.rs
> +        let dag_instance = DAG {
accept your suggestion.

2023-05-16 08:15 UTC, kobayu858 commented on lib/src/output.rs
> +    let dag_set = DAGSet {
accept your suggestion.

2023-05-16 19:49 UTC, atsushi421 requested changes

2023-05-16 19:49 UTC, atsushi421 commented on lib/src/output_log.rs
> +    dag_set: Vec<DAGInfo>,
```suggestion
    eadh_dag_info: Vec<DAGInfo>,
```

2023-05-17 01:09 UTC, kobayu858 commented on lib/src/output_log.rs
> +    dag_set: Vec<DAGInfo>,
accept your suggestion.

2023-05-17 01:15 UTC, atsushi421 approved these changes
LGTM！

2023-05-17 01:15 UTC, merged